# =============================================
# Étape 2 : Activation Spring Boot Actuator
# =============================================

# Exposition de tous les endpoints de supervision
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoints.web.base-path=/actuator
management.info.env.enabled=true

# Informations personnalisées
info.app.name=Spring Monitoring App
info.app.version=1.0.0
info.app.description=TP8 - Supervision et Logging Spring Boot

# =============================================
# Étape 3 : Journalisation (Logging)
# =============================================

# Niveau global des logs
logging.level.root=INFO

# Niveau DEBUG pour notre package
logging.level.ma.ens.tp8monitoring=DEBUG

# Enregistrement dans un fichier
logging.file.name=logs/application.log

# Format du log console : heure [thread] niveau logger - message
logging.pattern.console=%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n

# =============================================
# Étape 4 : Export métriques vers Prometheus
# =============================================

management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# =============================================
# Port de l'application
# =============================================
server.port=8080
